// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vizallas.Data;

#nullable disable

namespace vizallas.Migrations
{
    [DbContext(typeof(VizallasContext))]
    [Migration("20250930112251_sqlite_migration_872")]
    partial class sqlite_migration_872
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("vizallas.Models.Vizallas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folyo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Varos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VizallaS")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vizallas");
                });
#pragma warning restore 612, 618
        }
    }
}
